name: A workflow for the helloworld action
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions-a
        with:
          MY_NAME: "Foo"
      
